name: Post Merge Check
# Run extra build and checks to ensure `main` is functioning right.
# Runs all build and checks for linting, test, and build.

on:
  push:
    branches: [ "main" ]

jobs:
  android-post-check:

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check file changes
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            src:
              - 'app/**'
              - 'data-model/**'
              - 'service/**'
              - 'gradle/**'
              - 'build.gradle.kts'
              - 'settings.gradle.kts'
              - 'gradle.properties'
              - 'gradlew'
              - 'keystore/**'
              - '.github/workflows/android.yml'
              - '.github/workflows/android-lint.yml'
              - '.github/workflows/kover.yml'
              - '.github/workflows/diffuse.yml'

      - name: set up JDK
        if: steps.filter.outputs.src == 'true'
        uses: actions/setup-java@v5
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: gradle

      # Android SDK setup for GitHub Actions
      # https://github.com/android-actions/setup-android
      - name: Setup Android SDK
        if: steps.filter.outputs.src == 'true'
        uses: android-actions/setup-android@v4

      # Automatic gradle caching using `actions/cache@v4`
      # https://github.com/gradle/actions/tree/main/setup-gradle
      - name: Setup Gradle
        if: steps.filter.outputs.src == 'true'
        uses: gradle/actions/setup-gradle@v6

      - name: Run Linter
        if: steps.filter.outputs.src == 'true'
        run: ./gradlew lint

      - name: Build with Gradle
        if: steps.filter.outputs.src == 'true'
        run: ./gradlew build

      - name: Archive Problems Report
        if: failure() && steps.filter.outputs.src == 'true'
        uses: actions/upload-artifact@v7
        with:
          name: build-report-${{ github.run_id }}
          path: app/build/reports/**