name: Post Merge Check
# Run extra build and checks to ensure `main` is functioning right.
# Runs all build and checks for linting, test, and build.

on:
  push:
    branches: [ "main" ]

jobs:
  android-post-check:

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Automatic gradle caching using `actions/cache@v4`
      # https://github.com/gradle/actions/tree/main/setup-gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Linter
        run: ./gradlew lint

      - name: Build with Gradle
        run: ./gradlew build

      - name: Archive Problems Report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: build-report-${{ github.run_id }}
          path: app/build/reports/**